version: '3.5'

services:

    vernemq:
        environment:
            - DOCKER_VERNEMQ_ACCEPT_EULA=yes
            - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
            - MQTT_TOPIC=thndr-trading
        image: erlio/docker-vernemq
        ports:
            - "1883:1883"

    streamer:
        environment:
            - MQTT_HOST=vernemq
            - MQTT_PORT=1883
            - MQTT_TOPIC=thndr-trading
        image: thndr/streamer:0.2
        depends_on:
            - vernemq

    postgres_db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: thndr
        ports:
            - 5432:5432

    postgres_adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - postgres_db



